// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApYaFI8nq8HnfUTh3cE_9LBiVbpV6ynKg',
    appId: '1:472419981708:web:e32e9ceae8436c8d589ea9',
    messagingSenderId: '472419981708',
    projectId: 'geometry-app-cf890',
    authDomain: 'geometry-app-cf890.firebaseapp.com',
    storageBucket: 'geometry-app-cf890.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0nhzGb5fmmpk2sQLviuptpW7XrXlFwmA',
    appId: '1:472419981708:android:193cce41dbc8e4f6589ea9',
    messagingSenderId: '472419981708',
    projectId: 'geometry-app-cf890',
    storageBucket: 'geometry-app-cf890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrMWpYLEIqwt1KOErm6FmmfuNuiRQKkyQ',
    appId: '1:472419981708:ios:d5d8fa3a1549a6c9589ea9',
    messagingSenderId: '472419981708',
    projectId: 'geometry-app-cf890',
    storageBucket: 'geometry-app-cf890.firebasestorage.app',
    iosBundleId: 'com.example.geometryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrMWpYLEIqwt1KOErm6FmmfuNuiRQKkyQ',
    appId: '1:472419981708:ios:d5d8fa3a1549a6c9589ea9',
    messagingSenderId: '472419981708',
    projectId: 'geometry-app-cf890',
    storageBucket: 'geometry-app-cf890.firebasestorage.app',
    iosBundleId: 'com.example.geometryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApYaFI8nq8HnfUTh3cE_9LBiVbpV6ynKg',
    appId: '1:472419981708:web:8d90722702b62e4c589ea9',
    messagingSenderId: '472419981708',
    projectId: 'geometry-app-cf890',
    authDomain: 'geometry-app-cf890.firebaseapp.com',
    storageBucket: 'geometry-app-cf890.firebasestorage.app',
  );
}
